package de.autovermietung.onlinesystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-23T08:39:28.903+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "OnlineAdminIntegrationService", 
                  wsdlLocation = "http://localhost:8080/Autovermietung_OnlineSystem/OnlineAdminIntegration?wsdl",
                  targetNamespace = "http://onlineSystem.autovermietung.de/") 
public class OnlineAdminIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://onlineSystem.autovermietung.de/", "OnlineAdminIntegrationService");
    public final static QName OnlineAdminIntegrationPort = new QName("http://onlineSystem.autovermietung.de/", "OnlineAdminIntegrationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Autovermietung_OnlineSystem/OnlineAdminIntegration?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnlineAdminIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Autovermietung_OnlineSystem/OnlineAdminIntegration?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnlineAdminIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnlineAdminIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlineAdminIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnlineAdminIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnlineAdminIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnlineAdminIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OnlineAdminIntegration
     */
    @WebEndpoint(name = "OnlineAdminIntegrationPort")
    public OnlineAdminIntegration getOnlineAdminIntegrationPort() {
        return super.getPort(OnlineAdminIntegrationPort, OnlineAdminIntegration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineAdminIntegration
     */
    @WebEndpoint(name = "OnlineAdminIntegrationPort")
    public OnlineAdminIntegration getOnlineAdminIntegrationPort(WebServiceFeature... features) {
        return super.getPort(OnlineAdminIntegrationPort, OnlineAdminIntegration.class, features);
    }

}
