package de.autovermietung.onlinesystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-23T08:39:28.841+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://onlineSystem.autovermietung.de/", name = "OnlineAdminIntegration")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
public interface OnlineAdminIntegration {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllAA", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllAA")
    @WebMethod
    @ResponseWrapper(localName = "getAllAAResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllAAResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllAA(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteDreck", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.DeleteDreck")
    @WebMethod
    @ResponseWrapper(localName = "deleteDreckResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.DeleteDreckResponse")
    public de.autovermietung.onlinesystem.DeleteResponse deleteDreck(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "DreckId", targetNamespace = "")
        int dreckId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAuto", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAuto")
    @WebMethod
    @ResponseWrapper(localName = "saveAutoResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAutoResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveAuto(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Autoid", targetNamespace = "")
        int autoid,
        @WebParam(name = "bez", targetNamespace = "")
        java.lang.String bez,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "Zahlungbestaetigen", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.Zahlungbestaetigen")
    @WebMethod(operationName = "Zahlungbestaetigen")
    @ResponseWrapper(localName = "ZahlungbestaetigenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.ZahlungbestaetigenResponse")
    public de.autovermietung.onlinesystem.UpdateResponse zahlungbestaetigen(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Rechnungsid", targetNamespace = "")
        int rechnungsid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDreck", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllDreck")
    @WebMethod
    @ResponseWrapper(localName = "getAllDreckResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllDreckResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllDreck(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllKS", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllKS")
    @WebMethod
    @ResponseWrapper(localName = "getAllKSResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllKSResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllKS(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAA", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAA")
    @WebMethod
    @ResponseWrapper(localName = "saveAAResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAAResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveAA(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid,
        @WebParam(name = "beschreibung", targetNamespace = "")
        java.lang.String beschreibung,
        @WebParam(name = "kofferraumvolumen", targetNamespace = "")
        int kofferraumvolumen,
        @WebParam(name = "kraftstoffverbrauch", targetNamespace = "")
        java.lang.String kraftstoffverbrauch,
        @WebParam(name = "ks", targetNamespace = "")
        int ks,
        @WebParam(name = "marke", targetNamespace = "")
        int marke,
        @WebParam(name = "pjk", targetNamespace = "")
        double pjk,
        @WebParam(name = "ps", targetNamespace = "")
        int ps,
        @WebParam(name = "sitzanzahl", targetNamespace = "")
        int sitzanzahl
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAABild", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAABild")
    @WebMethod
    @ResponseWrapper(localName = "getAABildResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAABildResponse")
    public de.autovermietung.onlinesystem.AutoArtBildResponse getAABild(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveKS", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveKS")
    @WebMethod
    @ResponseWrapper(localName = "saveKSResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveKSResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveKS(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "KSId", targetNamespace = "")
        int ksId,
        @WebParam(name = "KSbezeichnung", targetNamespace = "")
        java.lang.String kSbezeichnung
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveKunde", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveKunde")
    @WebMethod
    @ResponseWrapper(localName = "saveKundeResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveKundeResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveKunde(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Kundeemail", targetNamespace = "")
        java.lang.String kundeemail,
        @WebParam(name = "kvorname", targetNamespace = "")
        java.lang.String kvorname,
        @WebParam(name = "knachname", targetNamespace = "")
        java.lang.String knachname,
        @WebParam(name = "fsnummer", targetNamespace = "")
        java.lang.String fsnummer,
        @WebParam(name = "pan", targetNamespace = "")
        java.lang.String pan,
        @WebParam(name = "aktive", targetNamespace = "")
        boolean aktive,
        @WebParam(name = "admin", targetNamespace = "")
        boolean admin,
        @WebParam(name = "strasse", targetNamespace = "")
        java.lang.String strasse
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllKunden", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllKunden")
    @WebMethod
    @ResponseWrapper(localName = "getAllKundenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllKundenResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllKunden(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createMarke", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateMarke")
    @WebMethod
    @ResponseWrapper(localName = "createMarkeResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateMarkeResponse")
    public de.autovermietung.onlinesystem.NeuerEintragResponse createMarke(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Markenname", targetNamespace = "")
        java.lang.String markenname
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllMarken", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllMarken")
    @WebMethod
    @ResponseWrapper(localName = "getAllMarkenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllMarkenResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllMarken(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getKunde", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetKunde")
    @WebMethod
    @ResponseWrapper(localName = "getKundeResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetKundeResponse")
    public de.autovermietung.onlinesystem.KundeResponse getKunde(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Kundeemail", targetNamespace = "")
        java.lang.String kundeemail
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveRechnung", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveRechnung")
    @WebMethod
    @ResponseWrapper(localName = "saveRechnungResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveRechnungResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveRechnung(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Rechnungsid", targetNamespace = "")
        int rechnungsid,
        @WebParam(name = "Rabatt", targetNamespace = "")
        java.lang.String rabatt
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAABild", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAABild")
    @WebMethod
    @ResponseWrapper(localName = "saveAABildResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveAABildResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveAABild(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid,
        @WebParam(name = "Bild", targetNamespace = "")
        java.lang.String bild
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRechnungsRabatt", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetRechnungsRabatt")
    @WebMethod
    @ResponseWrapper(localName = "getRechnungsRabattResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetRechnungsRabattResponse")
    public de.autovermietung.onlinesystem.RechnungsrabattResponse getRechnungsRabatt(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Rechnungsid", targetNamespace = "")
        int rechnungsid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createAllRechungen", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAllRechungen")
    @WebMethod
    @ResponseWrapper(localName = "createAllRechungenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAllRechungenResponse")
    public de.autovermietung.onlinesystem.NeuerEintragResponse createAllRechungen(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteSchaden", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.DeleteSchaden")
    @WebMethod
    @ResponseWrapper(localName = "deleteSchadenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.DeleteSchadenResponse")
    public de.autovermietung.onlinesystem.DeleteResponse deleteSchaden(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "SchadenId", targetNamespace = "")
        int schadenId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "Adminlogin", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.Adminlogin")
    @WebMethod(operationName = "Adminlogin")
    @ResponseWrapper(localName = "AdminloginResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.AdminloginResponse")
    public de.autovermietung.onlinesystem.KundenLoginResponse adminlogin(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllSchaeden", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllSchaeden")
    @WebMethod
    @ResponseWrapper(localName = "getAllSchaedenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllSchaedenResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllSchaeden(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createKS", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateKS")
    @WebMethod
    @ResponseWrapper(localName = "createKSResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateKSResponse")
    public de.autovermietung.onlinesystem.NeuerEintragResponse createKS(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "KS", targetNamespace = "")
        java.lang.String ks
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveMarke", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveMarke")
    @WebMethod
    @ResponseWrapper(localName = "saveMarkeResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveMarkeResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveMarke(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "MarkenId", targetNamespace = "")
        int markenId,
        @WebParam(name = "Markenname", targetNamespace = "")
        java.lang.String markenname
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAA", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAA")
    @WebMethod
    @ResponseWrapper(localName = "getAAResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAAResponse")
    public de.autovermietung.onlinesystem.AutoArtResponse getAA(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveRechnungsRabatt", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveRechnungsRabatt")
    @WebMethod
    @ResponseWrapper(localName = "saveRechnungsRabattResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.SaveRechnungsRabattResponse")
    public de.autovermietung.onlinesystem.UpdateResponse saveRechnungsRabatt(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Rechnungsid", targetNamespace = "")
        int rechnungsid,
        @WebParam(name = "Rabatt", targetNamespace = "")
        double rabatt
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllAutos", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllAutos")
    @WebMethod
    @ResponseWrapper(localName = "getAllAutosResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllAutosResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllAutos(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRechnung", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetRechnung")
    @WebMethod
    @ResponseWrapper(localName = "getRechnungResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetRechnungResponse")
    public de.autovermietung.onlinesystem.RechnungsAResponse getRechnung(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Rechnungsid", targetNamespace = "")
        int rechnungsid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAuto", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAuto")
    @WebMethod
    @ResponseWrapper(localName = "getAutoResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAutoResponse")
    public de.autovermietung.onlinesystem.AutoResponse getAuto(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "Autoid", targetNamespace = "")
        int autoid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createAA", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAA")
    @WebMethod
    @ResponseWrapper(localName = "createAAResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAAResponse")
    public de.autovermietung.onlinesystem.NeuerEintragResponse createAA(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "beschreibung", targetNamespace = "")
        java.lang.String beschreibung,
        @WebParam(name = "kofferraumvolumen", targetNamespace = "")
        int kofferraumvolumen,
        @WebParam(name = "kraftstoffverbrauch", targetNamespace = "")
        java.lang.String kraftstoffverbrauch,
        @WebParam(name = "ks", targetNamespace = "")
        int ks,
        @WebParam(name = "marke", targetNamespace = "")
        int marke,
        @WebParam(name = "pjk", targetNamespace = "")
        double pjk,
        @WebParam(name = "ps", targetNamespace = "")
        int ps,
        @WebParam(name = "sitzanzahl", targetNamespace = "")
        int sitzanzahl
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getKS", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetKS")
    @WebMethod
    @ResponseWrapper(localName = "getKSResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetKSResponse")
    public de.autovermietung.onlinesystem.KsResponse getKS(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "KSId", targetNamespace = "")
        int ksId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMarke", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetMarke")
    @WebMethod
    @ResponseWrapper(localName = "getMarkeResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetMarkeResponse")
    public de.autovermietung.onlinesystem.MarkeResponse getMarke(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "MarkenId", targetNamespace = "")
        int markenId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllRechnungen", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllRechnungen")
    @WebMethod
    @ResponseWrapper(localName = "getAllRechnungenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.GetAllRechnungenResponse")
    public de.autovermietung.onlinesystem.GetAllResponse getAllRechnungen(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createAuto", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAuto")
    @WebMethod
    @ResponseWrapper(localName = "createAutoResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.CreateAutoResponse")
    public de.autovermietung.onlinesystem.NeuerEintragResponse createAuto(
        @WebParam(name = "Sessionid", targetNamespace = "")
        int sessionid,
        @WebParam(name = "bez", targetNamespace = "")
        java.lang.String bez,
        @WebParam(name = "AAid", targetNamespace = "")
        int aAid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "emailbestaetigen", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.Emailbestaetigen")
    @WebMethod
    @ResponseWrapper(localName = "emailbestaetigenResponse", targetNamespace = "http://onlineSystem.autovermietung.de/", className = "de.autovermietung.onlinesystem.EmailbestaetigenResponse")
    public de.autovermietung.onlinesystem.UpdateResponse emailbestaetigen(
        @WebParam(name = "Hash", targetNamespace = "")
        java.lang.String hash
    );
}
